# Import libraries and Read Data

In [445]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [446]:
df_train = pd.read_csv("train.csv")
y_train = df_train["SalePrice"]
df_train.drop(columns=["SalePrice"],inplace=True)
df_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [447]:
df_test = pd.read_csv("test.csv")
df_test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [448]:
df = pd.concat([df_train,df_test])
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [449]:
df.reset_index(inplace=True,drop=True)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

# Drop Duplicates

In [450]:
df.drop_duplicates(inplace=True)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

# Handling Nulls

#### Exploring Nulls

In [451]:
nulls = df.isnull().sum()
nulls[nulls > 0].reset_index().sort_values(by=0,ascending=False)

           index     0
30        PoolQC  2909
32   MiscFeature  2814
2          Alley  2721
31         Fence  2348
22   FireplaceQu  1420
1    LotFrontage   486
25  GarageFinish   159
28    GarageQual   159
29    GarageCond   159
24   GarageYrBlt   159
23    GarageType   157
10  BsmtExposure    82
9       BsmtCond    82
8       BsmtQual    81
13  BsmtFinType2    80
11  BsmtFinType1    79
6     MasVnrType    24
7     MasVnrArea    23
0       MSZoning     4
18  BsmtFullBath     2
19  BsmtHalfBath     2
21    Functional     2
3      Utilities     2
27    GarageArea     1
26    GarageCars     1
17    Electrical     1
20   KitchenQual     1
16   TotalBsmtSF     1
15     BsmtUnfSF     1
14    BsmtFinSF2     1
12    BsmtFinSF1     1
5    Exterior2nd     1
4    Exterior1st     1
33      SaleType     1

In [452]:
df["LotFrontage"].value_counts()

60.0     276
80.0     137
70.0     133
50.0     117
75.0     105
        ...
144.0      1
111.0      1
123.0      1
155.0      1
31.0       1
Name: LotFrontage, Length: 128, dtype: int64

In [453]:
df["PoolQC"].value_counts()

Ex    4
Gd    4
Fa    2
Name: PoolQC, dtype: int64

In [454]:
df["PoolArea"].value_counts()

0      2906
144       1
228       1
368       1
444       1
480       1
512       1
576       1
648       1
738       1
800       1
519       1
555       1
561       1
Name: PoolArea, dtype: int64

In [455]:
df["MasVnrArea"].value_counts()

0.0       1738
120.0       15
200.0       13
176.0       13
216.0       12
          ...
167.0        1
731.0        1
394.0        1
886.0        1
1159.0       1
Name: MasVnrArea, Length: 444, dtype: int64

In [456]:
df["Electrical"].value_counts()

SBrkr    2671
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: Electrical, dtype: int64

In [457]:
df["BsmtFinSF1"].value_counts()

0.0       929
24.0       27
16.0       14
300.0       9
384.0       8
         ...
952.0       1
607.0       1
440.0       1
1236.0      1
1178.0      1
Name: BsmtFinSF1, Length: 991, dtype: int64

In [458]:
df["BsmtFinSF2"].value_counts()

0.0      2571
294.0       5
180.0       5
168.0       3
162.0       3
         ...
382.0       1
449.0       1
350.0       1
499.0       1
208.0       1
Name: BsmtFinSF2, Length: 272, dtype: int64

In [459]:
df["BsmtUnfSF"].value_counts()

0.0       241
384.0      19
728.0      14
672.0      13
600.0      12
         ...
1041.0      1
1272.0      1
465.0       1
551.0       1
1211.0      1
Name: BsmtUnfSF, Length: 1135, dtype: int64

In [460]:
df["BsmtFullBath"].value_counts()

0.0    1705
1.0    1172
2.0      38
3.0       2
Name: BsmtFullBath, dtype: int64

In [461]:
df["BsmtHalfBath"].value_counts()

0.0    2742
1.0     171
2.0       4
Name: BsmtHalfBath, dtype: int64

In [462]:
df["GarageCars"].value_counts()

2.0    1594
1.0     776
3.0     374
0.0     157
4.0      16
5.0       1
Name: GarageCars, dtype: int64

In [463]:
df["TotalBsmtSF"].value_counts()

0.0       78
864.0     74
672.0     29
912.0     26
1040.0    25
          ..
494.0      1
551.0      1
1154.0     1
105.0      1
1570.0     1
Name: TotalBsmtSF, Length: 1058, dtype: int64

In [464]:
df["GarageArea"].value_counts()

0.0       157
576.0      97
440.0      96
240.0      69
484.0      68
         ...
1110.0      1
766.0       1
208.0       1
1043.0      1
428.0       1
Name: GarageArea, Length: 603, dtype: int64

#### Drop & Fill Nulls

In [465]:
df.drop(columns=['Alley'],inplace=True)

In [466]:
df.drop(columns=['MiscFeature'],inplace=True)
df["LotFrontage"] = df["LotFrontage"].fillna(60.0)
df["GarageCars"] = df["GarageCars"].fillna(2)
df["GarageArea"] = df["GarageArea"].fillna(0)
df["TotalBsmtSF"] = df["TotalBsmtSF"].fillna(0)
df["BsmtUnfSF"] = df["BsmtUnfSF"].fillna(0)
df["BsmtFinSF2"] = df["BsmtFinSF2"].fillna(0)
df["BsmtFullBath"] = df["BsmtFullBath"].fillna(0)
df["BsmtHalfBath"] = df["BsmtHalfBath"].fillna(0)
df["BsmtFinSF1"] = df["BsmtFinSF1"].fillna(0)
df["PoolQC"] = df["PoolQC"].fillna(0)
df["MasVnrArea"] = df["MasVnrArea"].fillna(0.0)
df["GarageYrBlt"]=df["GarageYrBlt"].fillna(0)
df["Fence"] = df["Fence"].fillna("None")
df["MasVnrType"] = df["MasVnrType"].fillna("None")
df["BsmtQual"] = df["BsmtQual"].fillna("None")
df["BsmtCond"] = df["BsmtCond"].fillna("None")
df["BsmtExposure"] = df["BsmtExposure"].fillna("None")
df["BsmtFinType1"] = df["BsmtFinType1"].fillna("None")
df["BsmtFinType2"] = df["BsmtFinType2"].fillna("None")
df["GarageType"]=df["GarageType"].fillna("None")
df["GarageFinish"]=df["GarageFinish"].fillna("None")
df["GarageQual"]=df["GarageQual"].fillna("None")
df["GarageCond"]=df["GarageCond"].fillna("None")
df["FireplaceQu"]=df["FireplaceQu"].fillna("None")
df["Electrical"]=df["Electrical"].fillna("SBrkr")
df["MSZoning"]=df["MSZoning"].fillna("None")
df["Utilities"]=df["Utilities"].fillna("None")
df["Exterior1st"]=df["Exterior1st"].fillna("None")
df["Exterior2nd"]=df["Exterior2nd"].fillna("None")
df["KitchenQual"]=df["KitchenQual"].fillna("None")
df["Functional"]=df["Functional"].fillna("None")
df["SaleType"]=df["SaleType"].fillna("None")

In [467]:
nulls = df.isnull().sum()
nulls[nulls > 0].reset_index()

Empty DataFrame
Columns: [index, 0]
Index: []

In [468]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,None,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,None,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,None,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,None,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,None,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,None,0,6,2006,WD,Normal
2915,2916,160,RM,21.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,None,0,4,2006,WD,Abnorml
2916,2917,20,RL,160.0,20000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,None,0,9,2006,WD,Abnorml
2917,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,MnPrv,700,7,2006,WD,Normal
2918,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,None,0,11,2006,WD,Normal

# Encoding

In [469]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
Length: 78, dtype: object

#### Split df Into Numerical & Categorical

In [470]:
df_categorical = df.select_dtypes(include=['object']).copy() #columns with type "Object"
df_categorical.head()

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,None,Attchd,RFn,TA,TA,Y,0,None,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,...,TA,Attchd,RFn,TA,TA,Y,0,None,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,TA,Attchd,RFn,TA,TA,Y,0,None,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,...,Gd,Detchd,Unf,TA,TA,Y,0,None,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,...,TA,Attchd,RFn,TA,TA,Y,0,None,WD,Normal

In [471]:
quantitative = [f for f in df.columns if df.dtypes[f] != 'object']
df_numerical = df[quantitative]
df_numerical

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,706.0,...,548.0,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,978.0,...,460.0,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,486.0,...,608.0,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,216.0,...,642.0,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,655.0,...,836.0,192,84,0,0,0,0,0,12,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,0.0,0,0,0,0,0,0,0,6,2006
2915,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,286.0,0,24,0,0,0,0,0,4,2006
2916,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,576.0,474,0,0,0,0,0,0,9,2006
2917,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,0.0,80,32,0,0,0,0,700,7,2006
2918,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,650.0,190,48,0,0,0,0,0,11,2006

#### Encoding Ordinal Categorical Data

In [472]:
cleanup_nums = {"Street":     {"Grvl": 0, "Pave": 1},
                "LotShape":   {"IR3": 0, "IR2": 1, "IR1": 2, "Reg": 3},
                "LandContour":{"Low": 0, "HLS":1, "Bnk": 2, "Lvl": 3},
                "Utilities":  {"ELO": 0, "NoSeWa":1, "NoSewr": 2, "AllPub": 3},
                "LandSlope":  {"Sev": 0, "Mod":1, "Gtl": 2}, 
                "ExterQual":  {"Po": 0, "Fa":1, "TA": 2, "Gd": 3, "Ex": 4},
                "ExterCond":  {"Po": 0, "Fa":1, "TA": 2, "Gd": 3, "Ex": 4},
                "BsmtQual":   {"None":0, "Po": 1, "Fa":2, "TA": 3, "Gd": 4, "Ex": 5},
                "Bsmtcond":   {"None":0, "Po": 1, "Fa":2, "TA": 3, "Gd": 4, "Ex": 5},
                "BsmtExposure":   {"None":0, "No": 1, "Mn":2, "Av": 3, "Gd": 4},
                "BsmtFinType1":   {"None":0, "Unf": 1, "LwQ":2, "Rec": 3, "BLQ": 4, "ALQ": 5, "GLQ": 6},
                "BsmtFinType2":   {"None":0, "Unf": 1, "LwQ":2, "Rec": 3, "BLQ": 4, "ALQ": 5, "GLQ": 6},
                "HeatingQC":  {"Po": 0, "Fa":1, "TA": 2, "Gd": 3, "Ex": 4},
                "CentralAir":  {"N": 0, "Y":1},
                "Electrical":  {"Mix": 0, "FuseP":1, "FuseF": 2, "FuseA": 3, "SBrkr": 4},
                "KitchenQual":  {"Po": 0, "Fa":1, "TA": 2, "Gd": 3, "Ex": 4},
                "Functional":  {"Sal": 0, "Sev":1, "Maj2": 2, "Maj1": 3, "Mod": 4, "Min2": 5, "Min1": 6, "Typ": 7},
                "FireplaceQu":  {"None":0, "Po": 1, "Fa":2, "TA": 3, "Gd": 4, "Ex": 5},
                "GarageFinish": {"None": 0, "Unf":1, "RFn": 2, "Fin": 3},
                "GarageQual":  {"None":0, "Po": 1, "Fa":2, "TA": 3, "Gd": 4, "Ex": 5},
                "GarageCond":  {"None":0, "Po": 1, "Fa":2, "TA": 3, "Gd": 4, "Ex": 5},
                "PoolQC":  {"None":0, "Po": 1, "Fa":2, "TA": 3, "Gd": 4, "Ex": 5},
                "Fence":  {"None":0, "MnWw": 1, "GdWo":2, "MnPrv": 3, "GdPrv": 4},
                "PavedDrive":  {"N": 0, "P":1, "Y": 2}, 
                
                
               }


df_categorical = df_categorical.replace(cleanup_nums)
df_categorical.head()

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,SaleType,SaleCondition
0,RL,1,3,3,3,Inside,2,CollgCr,Norm,Norm,...,0,Attchd,2,3,3,2,0,0,WD,Normal
1,RL,1,3,3,3,FR2,2,Veenker,Feedr,Norm,...,3,Attchd,2,3,3,2,0,0,WD,Normal
2,RL,1,2,3,3,Inside,2,CollgCr,Norm,Norm,...,3,Attchd,2,3,3,2,0,0,WD,Normal
3,RL,1,2,3,3,Corner,2,Crawfor,Norm,Norm,...,4,Detchd,1,3,3,2,0,0,WD,Abnorml
4,RL,1,2,3,3,FR2,2,NoRidge,Norm,Norm,...,3,Attchd,2,3,3,2,0,0,WD,Normal

#### Encoding Nominal Categorical Data Using "One Hot Encoding"

In [473]:
df_categorical_nominal = df_categorical.select_dtypes(include=['object']).copy()
df_categorical_nominal

,MSZoning,Utilities,LotConfig,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,...,Exterior2nd,MasVnrType,Foundation,BsmtCond,Heating,KitchenQual,Functional,GarageType,SaleType,SaleCondition
0,RL,3,Inside,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,...,VinylSd,BrkFace,PConc,TA,GasA,3,7,Attchd,WD,Normal
1,RL,3,FR2,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,...,MetalSd,None,CBlock,TA,GasA,2,7,Attchd,WD,Normal
2,RL,3,Inside,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,...,VinylSd,BrkFace,PConc,TA,GasA,3,7,Attchd,WD,Normal
3,RL,3,Corner,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,...,Wd Shng,None,BrkTil,Gd,GasA,3,7,Detchd,WD,Abnorml
4,RL,3,FR2,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,...,VinylSd,BrkFace,PConc,TA,GasA,3,7,Attchd,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,RM,3,Inside,MeadowV,Norm,Norm,Twnhs,2Story,Gable,CompShg,...,CmentBd,None,CBlock,TA,GasA,2,7,None,WD,Normal
2915,RM,3,Inside,MeadowV,Norm,Norm,TwnhsE,2Story,Gable,CompShg,...,CmentBd,None,CBlock,TA,GasA,2,7,CarPort,WD,Abnorml
2916,RL,3,Inside,Mitchel,Norm,Norm,1Fam,1Story,Gable,CompShg,...,VinylSd,None,CBlock,TA,GasA,2,7,Detchd,WD,Abnorml
2917,RL,3,Inside,Mitchel,Norm,Norm,1Fam,SFoyer,Gable,CompShg,...,Wd Shng,None,PConc,TA,GasA,2,7,None,WD,Normal
2918,RL,3,Inside,Mitchel,Norm,Norm,1Fam,2Story,Gable,CompShg,...,HdBoard,BrkFace,PConc,TA,GasA,2,7,Attchd,WD,Normal

In [474]:
df_categorical_ordinal = df_categorical.drop(columns=list(df_categorical_nominal.columns))

In [475]:
OHE_results = pd.get_dummies(df_categorical_nominal, columns=list(df_categorical_nominal.columns))

In [476]:

OHE_results.drop(columns=['MasVnrType_None',"GarageType_None",'BsmtCond_None'],inplace=True)

In [477]:
OHE_results

,MSZoning_C (all),MSZoning_FV,MSZoning_None,MSZoning_RH,MSZoning_RL,MSZoning_RM,Utilities_1,Utilities_3,Utilities_None,LotConfig_Corner,...,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,0,1,0,0,1,0,1,...,0,0,0,1,1,0,0,0,0,0
4,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,0,0,0,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2915,0,0,0,0,0,1,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
2916,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
2917,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2918,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0

In [478]:
df_categorical_ordinal

,Street,LotShape,LandContour,LandSlope,ExterQual,ExterCond,BsmtQual,BsmtExposure,BsmtFinType1,BsmtFinType2,HeatingQC,CentralAir,Electrical,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
0,1,3,3,2,3,2,4,1,6,1,4,1,4,0,2,3,3,2,0,0
1,1,3,3,2,2,2,4,4,5,1,4,1,4,3,2,3,3,2,0,0
2,1,2,3,2,3,2,4,2,6,1,4,1,4,3,2,3,3,2,0,0
3,1,2,3,2,2,2,3,1,5,1,3,1,4,4,1,3,3,2,0,0
4,1,2,3,2,3,2,4,3,6,1,4,1,4,3,2,3,3,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,1,3,3,2,2,2,3,1,1,1,3,1,4,0,0,0,0,2,0,0
2915,1,3,3,2,2,2,3,1,3,1,2,1,4,0,1,3,3,2,0,0
2916,1,3,3,2,2,2,3,1,5,1,4,1,4,3,1,3,3,2,0,0
2917,1,3,3,2,2,2,4,3,6,1,2,1,4,0,0,0,0,2,0,3
2918,1,3,3,1,2,2,4,3,2,1,4,1,4,3,3,3,3,2,0,0

#### Concatenation After Encoding

In [479]:
df_encoded = pd.concat([df_numerical,OHE_results,df_categorical_ordinal], axis=1)
df_encoded

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,HeatingQC,CentralAir,Electrical,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
0,1,60,65.0,8450,7,5,2003,2003,196.0,706.0,...,4,1,4,0,2,3,3,2,0,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978.0,...,4,1,4,3,2,3,3,2,0,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486.0,...,4,1,4,3,2,3,3,2,0,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216.0,...,3,1,4,4,1,3,3,2,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655.0,...,4,1,4,3,2,3,3,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,3,1,4,0,0,0,0,2,0,0
2915,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,2,1,4,0,1,3,3,2,0,0
2916,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,4,1,4,3,1,3,3,2,0,0
2917,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,2,1,4,0,0,0,0,2,0,3
2918,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,4,1,4,3,3,3,3,2,0,0

In [480]:
[f for f in df_encoded.columns if df_encoded.dtypes[f] == 'object']

[]

# Model

#### split to original train-test

In [481]:
train = df_encoded[0:1460]
train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,HeatingQC,CentralAir,Electrical,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
0,1,60,65.0,8450,7,5,2003,2003,196.0,706.0,...,4,1,4,0,2,3,3,2,0,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978.0,...,4,1,4,3,2,3,3,2,0,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486.0,...,4,1,4,3,2,3,3,2,0,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216.0,...,3,1,4,4,1,3,3,2,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655.0,...,4,1,4,3,2,3,3,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0.0,...,4,1,4,3,2,3,3,2,0,0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790.0,...,2,1,4,3,1,3,3,2,0,3
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275.0,...,4,1,4,4,2,3,3,2,0,4
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49.0,...,3,1,3,0,1,3,3,2,0,0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830.0,...,3,1,4,0,3,3,3,2,0,0

In [482]:
x_train = train.drop(columns=['Id'])
x_train

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,HeatingQC,CentralAir,Electrical,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,4,1,4,0,2,3,3,2,0,0
1,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,4,1,4,3,2,3,3,2,0,0
2,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,4,1,4,3,2,3,3,2,0,0
3,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,3,1,4,4,1,3,3,2,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,4,1,4,3,2,3,3,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0.0,0.0,...,4,1,4,3,2,3,3,2,0,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790.0,163.0,...,2,1,4,3,1,3,3,2,0,3
1457,70,66.0,9042,7,9,1941,2006,0.0,275.0,0.0,...,4,1,4,4,2,3,3,2,0,4
1458,20,68.0,9717,5,6,1950,1996,0.0,49.0,1029.0,...,3,1,3,0,1,3,3,2,0,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830.0,290.0,...,3,1,4,0,3,3,3,2,0,0

In [483]:
y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [484]:
test = df_encoded[1460:]
test

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,HeatingQC,CentralAir,Electrical,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
1460,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,2,1,4,0,1,3,3,2,0,3
1461,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,2,1,4,0,1,3,3,2,0,0
1462,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,3,1,4,3,3,3,3,2,0,3
1463,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,4,1,4,4,3,3,3,2,0,0
1464,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,4,1,4,0,2,3,3,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,3,1,4,0,0,0,0,2,0,0
2915,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,2,1,4,0,1,3,3,2,0,0
2916,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,4,1,4,3,1,3,3,2,0,0
2917,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,2,1,4,0,0,0,0,2,0,3
2918,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,4,1,4,3,3,3,3,2,0,0

In [485]:
x_test = test.drop(columns=['Id'])
x_test

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,HeatingQC,CentralAir,Electrical,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
1460,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,2,1,4,0,1,3,3,2,0,3
1461,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,2,1,4,0,1,3,3,2,0,0
1462,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,3,1,4,3,3,3,3,2,0,3
1463,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,4,1,4,4,3,3,3,2,0,0
1464,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,4,1,4,0,2,3,3,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,3,1,4,0,0,0,0,2,0,0
2915,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,2,1,4,0,1,3,3,2,0,0
2916,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,4,1,4,3,1,3,3,2,0,0
2917,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,2,1,4,0,0,0,0,2,0,3
2918,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,4,1,4,3,3,3,3,2,0,0

#### ML Model

In [486]:
lin_reg = LinearRegression().fit(x_train, y_train)
lin_reg.coef_

array([-7.97610136e+01,  6.28359352e+01,  4.64633818e-01,  7.43812669e+03,
        5.33296718e+03,  2.94911578e+02,  9.18150781e+01,  2.76937281e+01,
        1.60700173e+01,  4.54862363e+00, -1.54339706e+00,  1.90752442e+01,
        1.60149370e+01,  3.39340371e+01, -2.01094149e+01,  2.98395441e+01,
        1.73250453e+03,  4.67729328e+02,  3.96256085e+03,  1.43217259e+03,
       -4.50223217e+03, -1.46869103e+04,  2.13453624e+03,  5.69485146e+03,
       -2.75657094e+01,  5.37957595e+03,  1.62263922e+01,  1.40259234e+01,
        1.32179516e+01, -2.50975528e+00,  3.20850793e+01,  3.36470944e+01,
       -5.99605781e+01, -8.81075896e-02, -6.14478496e+02, -1.13644562e+02,
       -2.23239393e+04,  1.22602841e+04, -2.32721504e-08,  5.16121549e+03,
        3.05250012e+03,  1.84993960e+03, -1.63691516e+04,  1.63691516e+04,
        3.64707375e-10,  2.78427852e+03,  1.33125110e+04, -2.80624125e+03,
       -1.57433333e+04,  2.45278500e+03,  1.47856551e+03,  1.34028234e+03,
        8.01598597e+03,  2.03559725e+03, -1.16318803e+04, -1.09311682e+04,
        1.89021906e+04, -1.48276459e+04, -8.86291441e+03, -4.62196121e+03,
       -4.31810570e+03, -1.56301850e+04, -1.05858938e+04,  1.03843753e+04,
       -1.47500422e+04,  2.43221389e+04,  2.20509396e+04, -7.31853578e+03,
       -5.45188356e+03, -3.81857776e+03, -2.70487053e+03, -4.90068654e+03,
        3.83065888e+04, -6.93382930e+03,  4.51515860e+02, -2.96113580e+03,
        2.07370712e+03,  9.89971190e+03,  6.12322625e+03,  4.90364489e+03,
       -1.86299558e+04,  5.69842978e+03, -1.18067532e+04,  4.69912485e+03,
        3.52783927e+04,  3.18345889e+04,  2.86953625e+04,  8.56057527e+04,
       -1.95626238e+05, -5.44398586e+04,  3.41174568e+04,  3.45345430e+04,
        7.83479243e+03,  8.91501741e+03,  1.25051152e+03, -1.08171776e+04,
       -7.18314374e+03,  9.89528740e+02,  1.33106989e+04,  7.71869578e+03,
       -8.95094607e+03, -9.35646203e+03, -5.41468593e+03, -1.47559702e+03,
        3.17876760e+03, -1.30570680e+04, -1.28546589e+04, -7.26151098e+03,
       -9.74975759e+03,  3.70526156e+02,  4.25524694e+04, -5.98883792e+05,
        7.25002595e+04,  1.15787743e+05,  8.84631579e+04,  5.12953780e+04,
        7.04444054e+04,  5.46733059e+04,  1.45719543e+05,  1.10450415e+04,
       -1.14409418e+04, -2.81785988e+03,  1.79496630e+04,  2.72947054e+03,
        6.34394562e+03, -1.49975499e+03, -3.37626581e+04,  8.05197104e+03,
       -9.45874490e-11, -6.00332071e+03,  6.35286862e+03,  6.73136348e+03,
       -3.04397626e+03, -2.52299870e+03,  1.88718667e+03, -3.16467136e+03,
       -2.97334340e+02,  1.10708229e+04, -4.02714580e+03,  2.72947054e+03,
        1.97987743e+03,  1.48184772e+03,  2.15537867e+04, -1.81447606e+03,
       -2.18278728e-10, -2.05689629e+04,  8.07122429e+02, -1.96826798e+04,
       -2.55241675e+03,  6.54228857e+03,  5.06187980e+03,  8.80590952e+02,
       -1.39482014e+04, -4.97609135e+03,  8.67820178e+02,  3.73810382e+03,
        6.40509809e+03,  7.49937556e+03, -1.45247407e+03,  1.32685217e+04,
       -2.94586251e+04, -4.39368565e+04, -4.46176526e+04, -1.15696386e+04,
       -4.23554657e+04, -1.09923854e+04,  6.33530361e+03, -6.61612478e+02,
        5.54474899e+03, -2.44004849e+04,  2.41744302e+04, -3.86815368e+03,
       -7.44158481e+03, -1.09517897e+04,  2.22615281e+04,  2.91038305e-11,
       -4.32662006e+04, -4.34573026e+02,  4.31163125e+02, -8.37879497e+00,
        1.25578551e+04,  8.84331040e+03,  2.18768238e+04,  1.36424205e-12,
        9.41585462e+03,  2.57299453e+04,  3.06550897e+04,  2.60762764e+04,
        3.45010231e+04,  2.89258889e+04, -1.42299181e+04,  6.10996101e+03,
        1.69167254e+04,  4.69630820e+03, -8.88441990e+03, -1.24370008e+04,
        2.87975387e+04,  0.00000000e+00, -5.63417897e+03, -1.53350155e+04,
       -9.17893022e+02,  6.49617604e+03,  7.18267327e+03,  8.15597042e+02,
        6.80672281e+03, -2.03832761e+04,  2.43424918e+04, -1.56426653e+02,
        1.30452584e+03,  9.86150050e+02,  4.46885109e+03, -2.48510225e+03,
        5.27512934e+03,  5.46282071e+03,  1.80257885e+02,  3.83275892e+02,
        1.55431123e+03, -6.83065079e+02, -6.97113311e+02, -1.51336892e+03,
       -3.55802811e+02,  7.99863059e+03, -2.32400580e+03,  1.36831413e+02,
        2.35554992e+04, -4.17550837e+02])

In [487]:
y_pred = lin_reg.predict(x_train)
r2 = r2_score(y_train,y_pred)
print(r2)

0.9242940515651034

In [488]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor().fit(x_train, y_train)

In [489]:
y_pred = dt.predict(x_train)
r2 = r2_score(y_train,y_pred)
print(r2)

1.0

# Prediction

In [490]:
prediction_tree = dt.predict(x_test)
prediction_reg = lin_reg.predict(x_test)

In [492]:
prediction_tree

array([129000., 155000., 192000., ..., 142500., 108000., 192000.])

In [493]:
prediction_reg

array([119708.92673276, 157442.39345558, 183282.19252161, ...,
       171155.86409552, 112904.31685284, 226958.44464389])